AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Hello World Lambda'
Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src
      Handler: lambda_hello_world.lambda_handler
      Runtime: python3.7
      Description: 'Hello World Lambda Function'
      AutoPublishAlias: prod
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'theo-test-lambda-s3-bucket'
